### ISSUE TITLE
iOS, preloadSimple: "Asset Not Found" on http assetPath

### ISSUE THREAD

**Issue by jvjvjv** [floatinghotpot/cordova-plugin-nativeaudio#103]
## Steps to reproduce

Try this:

```
window.plugins.NativeAudio.preloadSimple('music','http://incompetech.com/music/royalty-free/mp3-royaltyfree/Furious%20Freak.mp3',function(a){console.log("ok",a);},function(b){console.warn("no",b);});
```

(Or, upload your own MP3 to your own server and point to that path.)
## Expected result

The file has been preloaded so that I may play it back
## Actual result

The console logs the warning `no – "(NATIVE AUDIO) Asset not found. (http://incompetech.com/music/royalty-free/mp3-royaltyfree/Furious%20Freak.mp3)"` .
## Notes

This was just tested in iOS Simulators for 8.x, 9.x, and 10.x. None of them work.

My only guess is that `[[NSFileManager defaultManager] fileExistsAtPath : path]` does not check actual external URLs, so the preloadSimple. I've tried with a 3-minute song as well as a 5-second 'sound effect', and I receive the same error each time.

**Comment by dylanvdmerwe** [comment]
Same here. Any feedback on this issue?

**Comment by iliagerman** [comment]
I'm having the same issue, any news or workarounds?

**Comment by mr746866** [comment]
Is this issue solved?

**Comment by sambengtson** [comment]
Same issue here on Android

> java.io.FileNotFoundException: www/http://192.168.3.189:8080/calls/...

**Comment by floatinghotpot** [comment]
`www/http://192.168.3.189:8080/calls/...` is not a valid local file path.

This plugin does not support remote audio resource, yet. 

So, you need put the assets together with your js code.

**Comment by sambengtson** [comment]
@floatinghotpot I agree.  But the documentation does state that it supports this.  Wasn't until I looked at the source that I confirmed it wasn't supported  Certainly is misleading

**Comment by mydnic** [comment]
@floatinghotpot is it planned to be supported ? I'm looking to build an online radio app

**Comment by danielfliegauf** [comment]
Yes would be nice to know, and also good to remove it form documentation.

**Comment by howawong** [comment]
any update the issue? Why don't just update documentation. It makes all of us confused.

**Comment by rickybrown** [comment]
spent the last two hours "troubleshooting" this thinking i had an issue on the server, because I believed the documentation when it said "relative path or absolute URL (inluding http://)" ...

**Comment by desmondcain** [comment]
@rickybrown same here, which was frustrating given the docs. I ended up using the [Media](https://ionicframework.com/docs/native/media/) library and so far it's working as expected.

**Comment by dayvsonsales** [comment]
this is very frustrating, the documentation said that it works with URL, but this is not true.

**Comment by lina94** [comment]
Just bumped into this today while working with Ionic, the docs still says **"assetPath | string | the relative path or _absolute URL (inluding http://)_ to the audio asset."** (_inluding_ is another typo in the docs :)) 
I'm unable to play audio from external source (e.g. Firebase) and was wondering if there are any news on this? Am I doing something wrong or if not, is there a plan to support external source any time soon? Thanks!

**Comment by dayvsonsales** [comment]
@lina94 I had this issue a long time ago, I think this library is not supported anymore. I solved this problem using [cordova-plugin-media](https://github.com/apache/cordova-plugin-media)

**Comment by Topiya** [comment]
Anyone got any solution to play audio file using URL ?

**Comment by Topiya** [comment]
Anyone got solution to play audio file using URL ?

**Comment by jvjvjv** [comment]
It looks like music from remote servers was never supported. I'm closing this issue as won't fix.
