### ISSUE TITLE
Hardcoded www in java file

### ISSUE THREAD

**Issue by optikalefx** [floatinghotpot/cordova-plugin-nativeaudio#15]
lines 66 and 102 of the LowLatencyAudio.java file are hard coded with www. Our audio files are downloaded to the phones storage system, which live at cdvfile://localhost/persistent/...

And as far as I know there is no way to get from www to the external file system.

**Comment by fidoboy** [comment]
in ```int assetIntID = soundPool.load(fullPath, 1);``` can fullPath var be something in this way: ```http://localhost/sounds/mysound.mp3```? or there is any other required change to have it working?

**Comment by optikalefx** [comment]
localhost implies a local server, it has to be a root path starting with "/"

**Comment by fidoboy** [comment]
No, I need to access the file that way. Is it possible??

**Comment by optikalefx** [comment]
if you have a local web server running on the phone then you can access it that way. But I really don't think you have that situation.

**Comment by fidoboy** [comment]
Yes, I have it. Thanks, I'll try it that way to see if it works...

**Comment by fidoboy** [comment]
Well, it seems that it throws no error, but the sound isn't played... if i use the root path, then it works, but not when using localhost as path

**Comment by optikalefx** [comment]
You probably don't have a system webserver running. How are serving localhost?

**Comment by fidoboy** [comment]
Yes, localhost is running and, in fact, there are no errors when loading the sound file, problem is that the play command returns success (in javascript) but it doesn't sound at all...

**Comment by dhjw** [comment]
Can someone show exactly how/where to edit the current code to achieve this? :S
