### ISSUE TITLE
Unable to stop an already playing sound.

### ISSUE THREAD

**Issue by bummzack** [floatinghotpot/cordova-plugin-nativeaudio#20]
Using LowLatencyAudio 1.1.3 and Phonegap 3.5.0 there seems to be no way to stop an already playing sound. The sound keeps playing on Android and iOS.

Sound file was loaded using `lla.preloadAudio("music", "sound/music.mp3", 1, 1)`. There's no difference whether I use `play("music")` or `loop("music")` to start and `stop("music")` or `stop("music")` and `unload("music")` to stop a sound. It keeps playing no matter what I do.

**Comment by floatinghotpot** [comment]
Please update the plugin, and try again. Or, you can simply verify the plugin like this:
```bash
[sudo] npm install -g plugin-verify;
plugin-verify cordova-plugin-nativeaudio;
```
