### ISSUE TITLE
Friendly enquiry: Will you be working on a ios8 version?

### ISSUE THREAD

**Issue by tomswatermelon** [floatinghotpot/cordova-plugin-nativeaudio#22]
Hi, I have been using this plugin for playing audio file on iOS, but the plugin doesnt work on iOS SDK..
So I am wondering if you will be working on a iOS8 version, thanks!.

**Comment by kaansoral** [comment]
the simulators seem to lack the sound architecture, they also don't have sound settings

**Comment by Ajaxy** [comment]
Oh, damn. It was never mentioned anywhere. If it's so, I wasted much time on trying to figure out why it is not working. Will try it on real device now.

**Comment by Ajaxy** [comment]
It's working on real device. Please, add information about lack of Simulator support to the README file. It would save much time.

**Comment by floatinghotpot** [comment]
I verified it on both iOS and Android simulator, and both work. Try:
```bash
[sudo] npm install -g plugin-verify;
plugin-verify cordova-plugin-nativeaudio;
```
