### ISSUE TITLE
Problem compiling plugin

### ISSUE THREAD

**Issue by IanIppolito** [floatinghotpot/cordova-plugin-nativeaudio#30]
Hi,
I was using this plugin when it was located at https://github.com/floatinghotpot/cordova-plugin-lowlatencyaudio and it was working fine.  I see that the above repository redirects to this one now. So I tried recompiling but am getting an error. Can you please tell what is wrong? Thanks.

-compile:
    [javac] Compiling 42 source files to .../DollarCandy/platforms/android/ant-build/classes
    [javac] .../DollarCandy/platforms/android/src/com/rjfun/cordova/plugin/nativeaudio/NativeAudio.java:200: cannot find symbol
    [javac] symbol  : method setButtonPlumbedToJs(int,boolean)
    [javac] location: class org.apache.cordova.CordovaWebView
    [javac] 		this.webView.setButtonPlumbedToJs(KeyEvent.KEYCODE_VOLUME_DOWN, false);
    [javac] 		            ^
    [javac] .../DollarCandy/platforms/android/src/com/rjfun/cordova/plugin/nativeaudio/NativeAudio.java:201: cannot find symbol
    [javac] symbol  : method setButtonPlumbedToJs(int,boolean)
    [javac] location: class org.apache.cordova.CordovaWebView
    [javac] 		this.webView.setButtonPlumbedToJs(KeyEvent.KEYCODE_VOLUME_UP, false);
    [javac] 		            ^
    [javac] .../DollarCandy/platforms/android/src/com/rjfun/cordova/plugin/nativeaudio/NativeAudio.java:189: method does not override or implement a method from a supertype
    [javac] 	@Override
    [javac] 	^
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 3 errors

**Comment by floatinghotpot** [comment]
plugin verified with following commands:
```bash
[sudo] npm install -g plugin-verify
plugin-verify cordova-plugin-nativeaudio
```
