### ISSUE TITLE
preloadComplex doesn't work

### ISSUE THREAD

**Issue by kaansoral** [floatinghotpot/cordova-plugin-nativeaudio#32]
preloadComplex never worked for me, I liked how SidneyS initialized AVAudioSession, so I used his version of the plugin with LowLatencyAudio, which actually functioned

Now that the 2 plugins are combined, preloadComplex doesn't work again

preloadSimple works, yet preloadComplex doesn't, the success callback is triggered, there is no sound, I'm investigating

**Comment by kaansoral** [comment]
Comparatively, preloadSimple works, the sounds don't interfere/pause music, however the master volume level is used

Previously, NativeAudio+LowLatencyAudio+LowLatencyAudio routines used the app sound level, while also not pausing other playback (thanks to NativeAudio's AVAudioSession integration)

With current NativeAudio + preloadSimple, the volume control is missing, on default, the system sound level is very low and I don't think any regular iOS user is aware of it

With NativeAudio + preloadSimple, the UX is disturbing, as there is volume control, but the volume control controls nothing

**Comment by kaansoral** [comment]
I just tested .preloadComplex again, this time on iOS Simulator, similarly it doesn't work

I'm wondering what's the cause and how no one else complains about this issue, the .preloadAudio worked like a charm, I really wish the fork didn't merge into this plugin

Anyway, I will look into possible causes and solutions now, feel free to pitch in

**Comment by kaansoral** [comment]
I found the reason, I was going to send a PR, but I'm too lazy to do so, it's a simple solution

First, SidneyS made the assumption that preloadComplex would be used for music, so he used playWithFade, this is pretty reckless, people should fade in only when they want to fade in

I'm personally using preloadComplex for short sound effects, as I don't like the ios system audio / sound level logic

Anyway, this is the solution:

Replacing `[_asset playWithFade];` with `[_asset play];` at NativeAudio.m

**Comment by iamaro** [comment]
just wanted to say I had to update the xcode to do this as well -- forgot I had done this after reinstalling and was banging my head for a bit.

Could we get this updated so that preloadComplex only fades when you tell it to? I'm also using it for sound effects ( need the multi voices ) and it was really screwing with me!

Thanks

**Comment by Montoya** [comment]
Bump... this fix should be implemented...

**Comment by floatinghotpot** [comment]
fixed in commit c72e147427bf49e5978d36f14330e28575313971, thanks.

**Comment by gpaslari** [comment]
I guess this one should be reopened. I have exactly the same issue: preloadSimple works, while preloadComplex says file not found. Testing on iPhone SE iOS 10 and 5s, X - the same result

**Comment by giacomocerquone** [comment]
I've the exact same problem on android... preload simple works but not preload complex
