### ISSUE TITLE
asset not exist?

### ISSUE THREAD

**Issue by thedarkman123** [floatinghotpot/cordova-plugin-nativeaudio#34]
Im building a phonegap-build app and i added this there:

<gap:plugin name="de.neofonie.cordova.plugin.nativeaudio" version="3.0.2" />

this is the manual for it?

https://github.com/SidneyS/cordova-plugin-nativeaudio/tree/239e9f1c671df4accb424787f2d337181c7cc446

I have ios8 , i tried to do a simple load a sound and play it in loop.

In my build the file was in a folder named audio, and i did the following:

 window.plugins.NativeAudio.preloadComplex( 'music', 'audio/Sound.mp3', 1, 1, 0, function(msg){
    }, function(msg){
        console.log( 'error: ' + msg );
    });

 
    window.plugins.NativeAudio.loop( 'music' );

and i got an error saying "asset not exist ", What can be the cause of this?

**Comment by kaansoral** [comment]
And did it play afterwards?

For some reason none of my resources play with preloadComplex on iOS/iPod

**Comment by MiLeung** [comment]
Wait, what's the solution?  This shouldn't be closed?
