### ISSUE TITLE
Case sensitive MacOsx problem

### ISSUE THREAD

**Issue by Giacomololo** [floatinghotpot/cordova-plugin-nativeaudio#36]
Hi, I'm having trouble installing plugin on a MacOsx case sensitive system, because nativeaudio.h and nativeaudio.m files should be named NativeAudio.h and NativeAudio.m, as defined in your plugin.xml:

header-file src="src/ios/NativeAudio.h"/>
source-file src="src/ios/NativeAudio.m"/>

Can you fix it please?

Best regards
Giacomo

**Comment by floatinghotpot** [comment]
fixed, thanks for bug report. see: 4f251b912d1c5e9dc7b47ac7910e07ea6c8a7720
