### ISSUE TITLE
Not working on ios 8.3?

### ISSUE THREAD

**Issue by thedarkman123** [floatinghotpot/cordova-plugin-nativeaudio#37]
When i do the exact same code in the example, the success callback always called but there is no sound at all, what could be the cause of this?

is it because nativeaudio is not supporting 8.3 yet?

**Comment by thedarkman123** [comment]
Preload Simple works, lets see about that complex

**Comment by thedarkman123** [comment]
preload complex not working, closing because there is already an open issue, thank for the half baked plugin though

**Comment by kaansoral** [comment]
Thanks for the update :)

I'm going to dig in and use the older version of the plugin with the same AudioSession, somehow the combination achieved exactly what I wanted
