### ISSUE TITLE
WRITE_EXTERNAL_STORAGE required?

### ISSUE THREAD

**Issue by BBosman** [floatinghotpot/cordova-plugin-nativeaudio#39]
The plugin currently requires WRITE_EXTERNAL_STORAGE permissions.

Why/where is this needed? From a security perspective I would like to avoid requiring this permission, especially as I'm only using the plugin to play audio which shouldn't need write access somewhere.

**Comment by floatinghotpot** [comment]
I think it need buffer some steam on the storage path sometimes. You can double check the source code to confirm.
