### ISSUE TITLE
What is the difference between NativeAudio and LowLatencyAudio?

### ISSUE THREAD

**Issue by Ajaxy** [floatinghotpot/cordova-plugin-nativeaudio#40]
On PhoneGap Build plugins page there are two plugins pointing to the current repository:
NativeAudio: https://github.com/SidneyS/cordova-plugin-nativeaudio/blob/239e9f1/README.md
LowLatencyAudio: https://github.com/floatinghotpot/cordova-plugin-nativeaudio/blob/89fa228/README.md

What is the difference between them? Which one is more modern and should be used?

Actually I haven't managed to make any of them work:
— `LowLatencyAudio` does play sounds preloaded with `preloadAudio`, but fails ones, preloaded with `preloadFX`.
— `NativeAudio` simply crashes the app on the first sound (iOS 6.1 Simulator) *.

Thank you. 

UPD: * Managed to avoid crashes by passing more params (`{path}, {path}, 1, 1, 0`) to `preloadComplex` method. But still no effect of `preloadSimple`/`preloadFX` + `play` methods.

**Comment by kaansoral** [comment]
This one is the new/merged plugin: https://github.com/floatinghotpot/cordova-plugin-nativeaudio - it's @floatinghotpot's

You can find usages that work if you inspect the issues threads, there are some quirks

**Comment by Ajaxy** [comment]
@kaansoral, I didn't get you. Which one is the best to use? NativeAudio or LowLatencyAudio?
Thanks.

**Comment by floatinghotpot** [comment]
The plugin was initially named "LowLatencyAudio", then Sidney fork it and renamed to "NativeAudio" and  did heavy refactoring, later I merge the changes back, and did some bugfix.

So, basically, they are same thing, and the name "NativeAudio" is preferred.

**Comment by floatinghotpot** [comment]
Please see the newest master commit:
https://github.com/floatinghotpot/cordova-plugin-nativeaudio

**Comment by Ajaxy** [comment]
floatinghotpot , thank you, now it's clear. How to use the latest version with Phonegap Build right now? What is the right plugin name to add in `config.xml`? Thanks.

**Comment by floatinghotpot** [comment]
cordova-plugin-nativeaudio
