### ISSUE TITLE
Weird null pointer exception

### ISSUE THREAD

**Issue by gerbil** [floatinghotpot/cordova-plugin-nativeaudio#46]
Bug was found Nexus 9 (android).
Standard usage: preload, play, loop, stop.
`
W/System.err(13840): java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.concurrent.Callable.call()' on a null object reference
W/System.err(13840):    at de.neofonie.cordova.plugin.nativeaudio.NativeAudioAssetComplex.onCompletion(NativeAudioAssetComplex.java:165)
W/System.err(13840):    at android.media.MediaPlayer$EventHandler.handleMessage(MediaPlayer.java:2538)
W/System.err(13840):    at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err(13840):    at android.os.Looper.loop(Looper.java:135)
W/System.err(13840):    at android.app.ActivityThread.main(ActivityThread.java:5254)
W/System.err(13840):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(13840):    at java.lang.reflect.Method.invoke(Method.java:372)
W/System.err(13840):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
W/System.err(13840):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
`

**Comment by floatinghotpot** [comment]
Could you update the plugin and test again, if you can re-produce the problem, I will follow up.

**Comment by mDaiuto** [comment]
I have experienced this as well, although it didn't seem to cause any usability issues.

**Comment by sungwoncho** [comment]
I have this issue. It seems that when looping, `completeCallback` is null in `NativeAudioAssetComplex#onCompletion`. Any suggestions?

**Comment by floatinghotpot** [comment]
Fixed in merged PR. Thanks.
