### ISSUE TITLE
Audio Route changed you should listen to it

### ISSUE THREAD

**Issue by cucurbita** [floatinghotpot/cordova-plugin-nativeaudio#58]
Hello Raymond ; everything is within the title.

Best.

**Comment by kaansoral** [comment]
No offense but considering the pace of this plugin, you can't get anywhere with an issue that is vague at extremes

Even if you had a direct PR, it would probably take months for it to be live

**Comment by cucurbita** [comment]
Hello, 

it's only vague for people not knowing audio processing.
 
Best.
