### ISSUE TITLE
Initial [buggy] delay in playing on Android 6.0

### ISSUE THREAD

**Issue by thgie** [floatinghotpot/cordova-plugin-nativeaudio#74]
I load and play two complex after deviceReady. It worked fine on the emulator, but on a Z3 device I have an initial delay where just some scratching is heard. Then after a while the files play fine.

**Comment by kaansoral** [comment]
I never could get any android device play audio with a satisfactory performance

**Comment by thgie** [comment]
Do you have an alternative solution for playing multiple audiofiles
simultaneously?

On Fri, Feb 05, 2016 at 12:40 PM, kaansoral < notifications@github.com [notifications@github.com] > wrote:
I never could get any android device play audio with a satisfactory performance

—
Reply to this email directly or view it on GitHub
[https://github.com/floatinghotpot/cordova-plugin-nativeaudio/issues/74#issuecomment-180312424] .[https://github.com/notifications/beacon/AAsqIT90ZLKwTQPFmNQY6wcvkSTy8uT9ks5phIGxgaJpZM4HULHO.gif]

**Comment by kaansoral** [comment]
Unfortunately, no

I tried various settings/configurations, it always performed the same

My usage was basic "click"-like sounds, I ended up using native feedback, so I didn't push the issue further

I also thought specific types of audio could be causing the issues, so I tried various codecs I could find, indeed some seemed to play better

I mourn the time I spent on this issue, and I'm sorry I don't have anything tangible for you

-- -- --

Since your issue is "scratching" - a different audio encoding might solve your issue, my problem was more to do with performance and initial delay (at the <500ms range)

**Comment by thgie** [comment]
I might try native code, although I have no clue if it would resolve sich
problems.

On Sat, Feb 06, 2016 at 8:19 PM, kaansoral < notifications@github.com [notifications@github.com] > wrote:
Unfortunately, no

I tried various settings/configurations, it always performed the same

My usage was basic "click"-like sounds, I ended up using native feedback, so I
didn't push the issue further

I also thought specific types of audio could be causing the issues, so I tried
various codecs I could find, indeed some seemed to play better

I mourn the time I spent on this issue, and I'm sorry I don't have anything
tangible for you


--------------------------------------------------------------------------------

Since your issue is "scratching" - a different audio encoding might solve your
issue, my problem was more to do with performance and initial delay (at the
<500ms range)

—
Reply to this email directly or view it on GitHub
[https://github.com/floatinghotpot/cordova-plugin-nativeaudio/issues/74#issuecomment-180841649] .[https://github.com/notifications/beacon/AAsqIX9L0HVzBq5NuVhf1hNYByJD3cvvks5phj6zgaJpZM4HULHO.gif]

**Comment by kaansoral** [comment]
The plugin is already native code, try a different encoding instead

**Comment by thgie** [comment]
Ok, Thanks :) weil try.

On Sat, Feb 06, 2016 at 10:11 PM, kaansoral < notifications@github.com [notifications@github.com] > wrote:
The plugin is already native code, try a different encoding instead

—
Reply to this email directly or view it on GitHub
[https://github.com/floatinghotpot/cordova-plugin-nativeaudio/issues/74#issuecomment-180864082] .[https://github.com/notifications/beacon/AAsqIfFq4cTnnZuUcXF86wgKPOsM555rks5phljmgaJpZM4HULHO.gif]

**Comment by thgie** [comment]
I could resolve the issue by using ogg and loading and looping the files one after another. I got problems when I tried to start to loop two (or more) files at the same time. Loading the next file in the success function did it for me.
